.travis.yml
For https://www.npmjs.com/package/liquality
=> Push to gh-pages

package-lock.json, package.json, src/App.js
=> Add hotjar

package-lock.json, package.json
Update @liquality/chainabstractionlayer to 0.1.5
=> Update liquality cal 0.1.5

package-lock.json, package.json, src/actions/assets.js, src/components/CurrencyInput/CurrencyInput.scss, src/components/Rate/Rate.js, src/components/Rate/Rate.scss, src/components/WalletDisplay/WalletDisplay.scss, src/containers/CurrencyInputs/CurrencyInputs.js, src/reducers/assets.js, src/scss/variables.scss
This PR adds the Rate Component
It assumes a maximum decimal size of 6 decimals for either asset and the rate
=> Add rate component

src/utils/app-links.js
This PR adds rate to app-links
=> Add rate to app links

src/containers/CurrencyInputs/CurrencyInputs.js
Remove bug that keeps rate component on the swap completed screen
=> Remove rate component from completed

src/config/config.js, src/config/default.js, src/config/index.js, src/index.js, src/services/chainClient.js, src/utils/app-links.js
Beginnings of a config file that is used at build time.
=> App config file 

src/actions/swap.js
Simple alert when arriving at waiting screen to not close browser.
Obviously using alert is bad but didn't want to create too much overhead as backup link should come very soon.
=> Alpha warning

package-lock.json, package.json
Update CAL to version 0.1.16 to ensure that everything builds properly
=> Update CAL version

.travis.yml, .travis/liquality.io.swap-development.config.js, package-lock.json, package.json, src/actions/wallets.js
=> Add dev deploy

.travis/liquality.io.swap-challenge.config.js, .travis/liquality.io.swap.config.js, src/config/config.js, src/config/default.js, src/containers/LiqualitySwap/LiqualitySwap.js, src/index.scss
Adds a config that allows specifying a HTML footer for the app.
=> Footer config + Values for alpha

src/containers/CurrencyInputs/CurrencyInputs.js, src/containers/SwapInitiation/SwapInitiation.js
Disable inputs for party B , they should not be able to change terms.
=> Party b disable inputs

.travis/liquality.io.swap-challenge.config.js, src/config/default.js, src/containers/SwapCompleted/SwapCompleted.js, src/containers/SwapCompleted/SwapCompleted.scss
=> Show twitter button on swap completion

src/components/Button/Button.js
Describe the purpose of this PR, does it match DoD for what you are working on?
=> temp button fix

src/services/chainClient.js
This PR fixes a typo that was pushing for blocks to be estimated for 1 block, ending up with ridiculously high fees.
=> Fix fee estimation

src/actions/wallets.js
Use with https://github.com/liquality/chainabstractionlayer/pull/119
=> Use getUsedAddresses

package-lock.json, package.json, src/App.js, src/actions/secretparams.js, src/actions/swap.js, src/actions/transactions.js, src/components/BackupLinkCard/BackupLinkCard.js, src/history.js, src/store.js, src/utils/storage.js
Save the transactions to local storage and reload app state based on this.
=> Reloading state: Transactions writing and reading from local storage

src/actions/transactions.js, src/config/config.js, src/containers/SwapInitiation/SwapInitiation.js
This removes the requirement for minimum of 1 confirmation for swaps.
=> Midnight experiment

package-lock.json, package.json, src/App.js, src/actions/secretparams.js, src/actions/swap.js, src/actions/transactions.js, src/components/BackupLinkCard/BackupLinkCard.js, src/history.js, src/store.js, src/utils/storage.js
putting back the backup link functionality into dev branch
=> Backup link

package-lock.json, package.json, src/App.js, src/actions/swap.js, src/actions/transactions.js, src/components/BackupLinkCard/BackupLinkCard.js, src/history.js, src/store.js, src/utils/storage.js
Reverts liquality/liquality-swap#100
=> Revert "Revert "Backup link""

src/containers/LiqualitySwap/LiqualitySwap.js, src/containers/LiqualitySwap/LiqualitySwap.scss
Add swap challenge is over modal
=> Add swap challenge over modal

src/containers/LiqualitySwap/LiqualitySwap.js
=> Fix typo for swap challenge

.travis/liquality.io.swap-challenge.config.js, .travis/liquality.io.swap.config.js, package-lock.json, package.json, src/components/Button/Button.js, src/components/Button/Button.scss, src/components/WalletChoose/WalletChoose.js, src/components/WalletConnectPopup/WalletConnectPopup.js, src/components/WalletConnected/WalletConnected.js, src/services/chainClient.js, src/utils/networks.js
=> Wallet popup tweaks

src/actions/swap.js
Fixes 2 situations: 
1. When the wallet is not available and the wallet connection popup is shown, it should not display the previously connected wallet.
2. When locking funds, the UI was navigating to the next location while showing the wallet connection prompts. it should not do this.
=> Fix wallet check not clearing when unavailable

.travis/liquality.io.mainnet.config.js, .travis/liquality.io.testnet.config.js
=> Add sentry

src/components/WalletChoose/WalletChoose.js, src/utils/wallets.js
Adds links to help user connecting their wallets.
=> Added troubleshooting link in wallet configuration

.travis.yml
This PR instructs Travis to build UI for each commit as follows;
Mainnet: https://liquality.io/dev/COMMIT-HASH/swap
Testnet: https://liquality.io/dev/COMMIT-HASH/swap-testnet
=> Build all commits

package-lock.json, package.json, src/actions/swap.js
…fund)
When clicking on an action button (initiation/claim/refund), if a wallet connection is required, the UI will stop after wallet is connected instead of continuing to perform the action.
With this change, the UI continues after wallet is connected. No need to click the button again.
=> Fix issue with wallet connection not continuing action

package-lock.json, src/actions/transactions.js, src/services/chainClient.js, src/utils/app-links.js, src/utils/wallets.js
=> Backup link and ledger wallets text

package-lock.json, src/actions/swap.js
Remove checking the connection of party B while locking as it's enforced before and forces Ledger to disconnect and reconnect both parts
=> Ensure the correct wallet is connected while locking funds

public/config.js, public/index.html, src/config/index.js, src/index.js, src/services/chainClient.js
Adds a way to override the config after the application has been built.
This happens all in one place in a config file that can added to a build
=> Runtime config

src/containers/LiqualitySwap/LiqualitySwap.js, src/index.js, src/store.js, src/utils/app-links.js, src/utils/protocolHandler.js
Adds a process to accept `swap://` links for the purpose of quotes
=> Swap URI handler

.travis/liquality.io.mainnet.config.js, .travis/liquality.io.testnet.config.js
* Update liquality.io.mainnet.config.js
* Update liquality.io.testnet.config.js
=> Update Infura APIs (#193)

configs/liquality.io.mainnet.config.js, configs/liquality.io.testnet.config.js, src/config/config.js
=> blank screen fix implemented
